Test 3: Revision
Ayisha-Ahamed/Assignment pull request #12
Opened 2024-11-27 23:20 UTC by Ayisha-Ahamed

2024-12-03 15:45 UTC, sanjivtmm commented on Main.c
> +#include "TicTacToe.h"
It is a program you are implementing not a library. So it does not need to split into separate header and code files.

2024-12-03 15:45 UTC, sanjivtmm commented on Main.c
> +static wchar_t Get_Input (wchar_t* prompt) {
No comment/description of the function.
Nested while loop is making the logic obscure.
Use of continue seems suspect.

2024-12-03 15:45 UTC, sanjivtmm commented on Main.c
> +      if (c < L'1' || c > L'9' || arr[c - L'1'] != ' ') continue;
Avoid use of continue. Better to reverse the condition and exit.

2024-12-03 15:45 UTC, sanjivtmm commented on Main.c
> +      while (arr[num] != L' ') num = rand () % 9;
Nice idea to use random as the first level of auto play!

2024-12-03 15:45 UTC, sanjivtmm commented on TicTacToe.c
> +   static int Count[8][2] = {
Interesting data structure.

2024-12-12 06:28 UTC, Dakshita-Minocha commented
Please assign PRs to yourself before committing and pushing.

2024-12-12 06:50 UTC, Dakshita-Minocha requested changes

2024-12-12 06:50 UTC, Dakshita-Minocha commented on TicTacToe.c
> +   wprintf (L"\u250F\u2501\u2501\u2501\u2533\u2501\u2501\u2501\u2533\u2501\u2501\u2501\u2513\n\u2503");
You can directly copy paste symbols. It is more readable than corresponding unicode.

2024-12-12 06:50 UTC, Dakshita-Minocha commented on TicTacToe.c
> +      if (l >= 9) break;
```suggestion
   for (int i = 0, l = 0; i < 3 || l >= 9; i++) {
      for (int k = 0; k < 3; l++, k++) wprintf (L" %wc \u2503", grid[l]);
 

```

2024-12-12 06:50 UTC, Dakshita-Minocha commented on TicTacToe.c
> +   if (ModeChoice ()) isAutoPlay = true;
```suggestion
    isAutoPlay = ModeChoice ();

```

2024-12-12 06:50 UTC, Dakshita-Minocha commented on TicTacToe.c
> +      wprintf (L"%ls :\n", isPlayer1 ? L"Player 1" : L"Player 2");
```suggestion
      wprintf (L"Player %d :\n", isPlayer1 );

```
isPlayer1 can be an int with 1 and 2 as possible values.
Check if this simplifies implementation.

2024-12-17 07:31 UTC, Dakshita-Minocha commented on TicTacToe.c
> +static int TicTacToe (char* grid, int index, int Player) {
```suggestion
static int TicTacToe (char* grid, int index, int player) {

```

2024-12-17 07:31 UTC, Dakshita-Minocha commented on TicTacToe.c
> +   static int Count[8][2] = {
static variables start with s.
```suggestion
   static int sCount[8][2] = {

```

2024-12-17 07:31 UTC, Dakshita-Minocha commented on TicTacToe.c
> +static int Get_Box_Num (char* arr, bool isAutoPlay) {
Please follow naming conventions and read through a program before you submit.

2024-12-17 07:31 UTC, Dakshita-Minocha commented on TicTacToe.c
> +         return -1;
Why return here? Why not handle the scenario?

2024-12-19 06:09 UTC, Dakshita-Minocha approved these changes

2024-12-19 06:09 UTC, closed without merging