A4
Ayisha-Ahamed/Assignment pull request #5
Opened 2024-09-13 08:16 UTC by Ayisha-Ahamed

2024-09-14 02:25 UTC, gdineshkumar219 commented on palindrome.c
> +
In this method just return the reversed value. Don't  perform any other functionality

2024-09-14 02:25 UTC, gdineshkumar219 commented on palindrome.c
> +      if (isalnum (input[i])) string[idx++] = tolower (input[i]);
check this "isalnum" in function where you get input

2024-09-17 06:27 UTC, gdineshkumar219 commented on palindrome.c
> +
Remove empty lines

2024-09-17 06:27 UTC, gdineshkumar219 commented on test.c
> +   int len = (int)strlen (input), idx = 0;
len = strlen(input) is fine. Why you typecast it?

2024-09-17 06:27 UTC, gdineshkumar219 commented on test.c
> +   return 0;
![image](https://github.com/user-attachments/assets/e798ee5e-d661-4e0c-bbb2-e220fbc27a1a)
In this if I gave wrong option it is asking 3times why? Check it

2024-09-17 06:27 UTC, gdineshkumar219 commented on test.c
> +   return 0;
For inputs -121,123!@#$%abc , it should return false and give proper message like the given input is not a palindrome. But the actual implementation consider this as an invalid input

2024-09-17 06:27 UTC, gdineshkumar219 commented on test.c
>  int PrintTable () {
Make this method as void

2024-09-17 06:27 UTC, gdineshkumar219 commented on test.c
>        return;
Why are you returning here? In void

2024-09-17 15:00 UTC, gdineshkumar219 commented on palindrome.c
> +
Make this function to return int instead of string

2024-09-17 15:00 UTC, gdineshkumar219 commented on palindrome.c
> +}
Make this method as inline method

2024-09-17 15:00 UTC, gdineshkumar219 commented on palindrome.c
> +bool Palindrome (char* input, char* reverse) {
Give proper name to function, here the name is not proper

2024-09-17 15:00 UTC, gdineshkumar219 commented on palindrome.c
> +}
Shift this method to main(test.c)

2024-09-17 15:00 UTC, gdineshkumar219 commented on test.c
> +   int len = (int)strlen (input), i = 0;
len = strlen(input), casting is not required

2024-09-17 15:00 UTC, gdineshkumar219 commented on test.c
> +      if (len > 10 || str[0] == '-' && len > 11 || num + 1 < num || num - 1 > num) {      // For oveflow conditions the integer is taken as a string
Change the overflow logic. This takes 9999999 as valid. Please check it

2024-09-19 02:20 UTC, gdineshkumar219 reviewed
![image](https://github.com/user-attachments/assets/eb8fbcff-ca46-4f05-b5be-0689cf89c648)
why are you handle negative numbers like this?

2024-09-19 02:20 UTC, gdineshkumar219 commented on palindrome.c
> +bool IsPal (char* input, char* reverse) {
Refine further

2024-09-19 02:20 UTC, gdineshkumar219 commented on test.c
> +   char* strArr[10] = { "Malayalam",  "Was it a car or a cat I saw",  "I did,did I?",                                                 // String inputs
-1234321 for this input the reversed output should be 1234321-

2024-09-19 02:31 UTC, gdineshkumar219 commented
![image](https://github.com/user-attachments/assets/832f02d8-1ea1-485a-9e0b-7905c42aeabf)

1. if I give input like this , it will take .Actually it should not take that input.
2. In your code if I gave input as **'**, it consider it as an empty string

2024-10-05 02:45 UTC, gdineshkumar219 commented on test.c
> +
Remove empty lines

2024-10-05 02:45 UTC, gdineshkumar219 commented on ClassicLibrary.c
> +   if (revNum > INT_MAX || revNum < INT_MIN) return -1;     // If the reversed number is beyond the range of int, -1 is returned
instead of returning -1 return proper message

2024-10-05 02:45 UTC, gdineshkumar219 commented on Test.c
> +   int newCount = 0;
Declare along with line 30

2024-10-14 05:19 UTC, gdineshkumar219 commented on ClassicLibrary.c
> +   for (int end = strlen (input) - 1, start = 0; start <= end;) if (tolower (input[start++]) != tolower (input[end--])) return false;
instead of converting a string to lower better convert it using filter char and pass

2024-10-29 11:37 UTC, Dakshita-Minocha requested changes
Make changes as discussed and assign back.

2024-10-29 11:37 UTC, Dakshita-Minocha commented on Header.h
> +#define OVERFLOW -1                        // Indicates that the reversed number exceeds integer range
Comments are added in places where it is difficult to understand context or concept (neither of which is the case here)
```suggestion
#define OVERFLOW -1 

```

2024-10-29 11:37 UTC, Dakshita-Minocha commented on ClassicLibrary.c
> +   for (int end = strlen (input) - 1, start = 0; start <= end;) if (input[start++] != input[end--]) return false;
Nice

2024-11-02 07:56 UTC, Dakshita-Minocha requested changes

2024-11-02 07:56 UTC, Dakshita-Minocha commented on Test.c
> +   char* str;
Please follow naming conventions. Any Property/Field in a struct should start with a capital letter.
```suggestion
   char* String;

```

2024-11-02 07:56 UTC, Dakshita-Minocha commented on Test.c
> +   bool isPal;
```suggestion
   bool IsPal;

```

2024-11-02 07:56 UTC, Dakshita-Minocha commented on Test.c
> +char* Filter (char* input, bool* isNumCpy) {
![image](https://github.com/user-attachments/assets/ab93d5c7-b8d2-4a78-90fe-31a7bde6bf89)
Intellisense gives you recommendations for changes that'll help optimise your code. Please make these changes wherever valid.
See [here](https://stackoverflow.com/questions/572547/what-does-static-mean-in-c).

2024-11-02 07:56 UTC, Dakshita-Minocha commented on Test.c
> +      if (isdigit (input[k]) == 0) isNum = false;// Check if the input character is a digit.
```suggestion
       isNum = isdigit (input[k]);
```

2024-11-02 07:56 UTC, Dakshita-Minocha commented on Test.c
> +      if (isdigit (input[k]) == 0) isNum = false;// Check if the input character is a digit.
Currently, you are assigning isNum multiple times in a loop and you are checking with the current char only. Since you are disregarding the previous input, you could enter a char somewhere in the middle (which would mean isNum = false), and then a number (which would mean isNum = true in the next iteration). It causes this: 
![image](https://github.com/user-attachments/assets/62942ee3-4ec8-4c76-bda9-6df28bc00195)
The correct way is to take into account both the current and the previous value.

![image](https://github.com/user-attachments/assets/7d5f0bb6-0213-4d13-8ddc-97e21aa336f1)

2024-11-02 07:56 UTC, Dakshita-Minocha commented on Test.c
> +      if (isdigit (input[k]) == 0) isNum = false;// Check if the input character is a digit.
It also points out that you should always add test cases for each 'feature' you add.

2024-11-02 07:56 UTC, Dakshita-Minocha commented on Test.c
> +   if (!strcmp (str, "\\n") || !strcmp (str, "\\t") || !strcmp (str, "\\r") || !strcmp (input, EMPTY))
!a || !b = a && b;

2024-11-02 07:56 UTC, Dakshita-Minocha commented on Test.c
> +   char* input = Filter (str, &isNum);                                     // Filtered input string
```suggestion
   char* input = Filter (str, &isNum);                                    

```

2024-11-02 07:56 UTC, Dakshita-Minocha commented on Test.c
> +      char* reverseStr = NumToString (numRev, str);  // Converts the reversed number/ output message to a string
When the meaning of the code is clear, you should not add comments.

2024-11-02 07:56 UTC, Dakshita-Minocha commented on Test.c
> +   else if (isNum == true) {
if () takes boolean, isNum is also boolean. Please make this change wherever applicable.
if (isNum) is sufficient in most cases.

2024-11-02 07:56 UTC, Dakshita-Minocha commented on Test.c
> +      printf ("%s\n", (num >= 0) && (num == numRev) ? PAL_TRUE : PAL_FALSE);
num == numRev is the only relevant condition for palindrome

2024-11-02 07:56 UTC, Dakshita-Minocha commented on Test.c
> +   printf (""YELLOW "\tInput"RESET"\t\t"YELLOW"\t\tExpected Output"RESET"\t"
We do not use \t at metamation. Use 3 spaces instead. It ensures consistency across machines.

2024-11-02 07:56 UTC, Dakshita-Minocha commented on Test.c
> +   printf (""YELLOW "\tInput"RESET"\t\t"YELLOW"\t\tExpected Output"RESET"\t"
You don't need to set and reset color for every word. Once in a printf statement is enough (unless you're changing colors).

2024-11-02 07:56 UTC, Dakshita-Minocha commented on Test.c
> +      printf ("%s\n", (num >= 0) && (num == numRev) ? PAL_TRUE : PAL_FALSE);
Same comment for your test function TestReverseNum()

2024-11-02 07:56 UTC, Dakshita-Minocha commented on Test.c
> +   while (1) {
```suggestion
   while (choice) {

```

2024-11-02 07:57 UTC, Dakshita-Minocha commented
There are still warnings being displayed.
![image](https://github.com/user-attachments/assets/9999ec40-6068-41e4-a8c6-892e1c3eeab6)

2024-11-06 11:43 UTC, Dakshita-Minocha approved these changes

2024-11-06 11:43 UTC, closed without merging